name: flutter_application_last
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # Libreria per client InfluxDB
  influxdb_client: ^2.2.0

  # Libreria effetivo BLE
  flutter_reactive_ble: ^5.3.1
  # Gestione dei permessi
  permission_handler: ^8.1.6
  
flutter:
  uses-material-design: true

dev_dependencies: #richiesto dal compilatore
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  image_path: "assets/sshicon.png"